### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by tonytainguyen** [vieron/stylelint-webpack-plugin#1]
I was wondering if this also includes stylus support because I see that you mention sass/scss/css around your readme but not stylus :(

**Comment by vieron** [comment]
This plugin doesn't add any extra functionality to stylelint, and stylelint
in theory supports anything that can be parsed by PostCSS (as its written
in their documentantion).

El sábado, 16 de abril de 2016, Tony Tai Nguyen <notifications@github.com>
escribió:

> I was wondering if this also includes stylus support because I see that
> you mention sass/scss/css around your readme but not stylus :(
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vieron/stylelint-webpack-plugin/issues/1>
>


-- 
--

Javier Sánchez-Marín Martínez
javiersanchezmarin@gmail.com
