### ISSUE TITLE
Can you ignore files with this plugin?

### ISSUE THREAD

**Issue by kobeaerts** [vieron/stylelint-webpack-plugin#10]
__

**Comment by hauptrolle** [comment]
You can add an .stylelintignore to ignore specific directories/files. (See: http://stylelint.io/user-guide/configuration/#stylelintignore)

**Comment by JaKXz** [comment]
As @hauptrolle suggested, you can use the `.stylelintignore` file - this library's API essentially wraps `stylelint`'s node API in a webpack plugin, so [all stylelint options should work](https://github.com/vieron/stylelint-webpack-plugin#options).
