### ISSUE TITLE
Update stylelint dependency

### ISSUE THREAD

**Issue by isellsoap** [vieron/stylelint-webpack-plugin#14]
Current stylelint dependency is at `^6.0.1`, the latest stylelint version is `7.0.1`.

**Comment by tcstory** [comment]
yeah , i met the problem,when i use "stylelint-config-standard": "^11.0.0", it will report the following error
Error: Undefined rule "media-feature-parentheses-space-inside"

**Comment by cascornelissen** [comment]
Wouldn't it be possible to allow users to install a specific version of stylelint instead of including it in the package?
