### ISSUE TITLE
undefined rules

### ISSUE THREAD

**Issue by SuperheroUI** [vieron/stylelint-webpack-plugin#39]
I'm having trouble using the sass lint rules in .stylelintrc Can you provide some docs on the rules and any additional dependencies?

I have everything configured as your instructions indicate.

package.json includes: "stylelint-webpack-plugin": "^0.4.0",

webpack.config includes: 

const StyleLintPlugin = require('stylelint-webpack-plugin');

new StyleLintPlugin({
            syntax: 'scss',
            configFile: '.stylelintrc',
            files: ['*_/_.s?(a|c)ss'],
            failOnError: false,
        })

Am I missing a dependency?? When I run the linters I get
Error: Undefined rule nesting-depth

or 

Error: Undefined rule NestingDepth

Which is a valid rule, but what version of sass is being used?
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#bangformat
https://github.com/sasstools/sass-lint/blob/master/docs/rules/nesting-depth.md

**Comment by JaKXz** [comment]
Correct me if I'm wrong, but it sounds like you're trying to use `sass-lint` rules with [`stylelint`](http://stylelint.io/), which are two different linters entirely. `stylelint-webpack-plugin` will only run your code through `stylelint`.

**Comment by JaKXz** [comment]
@SuperheroUI I'm going to close this for now, feel free to re-open if you can provide more context specifically regarding `stylelint-webpack-plugin`. Thanks.

**Comment by joeHillman** [comment]
@SuperheroUI @JaKXz  - Just a note, it looks like they changed the media query parens inside to media feature in v7.0.
It was in the initial 1.0 version as media query parens inside.
https://github.com/stylelint/stylelint/blob/7.0.0/CHANGELOG.md

I saw the same issue recently on a project.
