### ISSUE TITLE
Lint undefined functions?

### ISSUE THREAD

**Issue by heurefugitive** [vieron/stylelint-webpack-plugin#42]
Hello!

I just started using stylelint so I probably haven't looked at all the docs. However, I was hoping it could lint my most common problem: lint undefined functions (due to missing `@import`ed file)

Does anyone mind pointing me in the right direction? I've gotten the impression it might have to do with some post-CSS shenanigans but I'm not sure where to start :(

**Comment by JaKXz** [comment]
Sounds like this should be an issue made directly to https://github.com/stylelint/stylelint or looked around on S/O - without more context or an example I can't help you much further. Good luck!
