### ISSUE TITLE
Throws error with stylelint@7.7.0

### ISSUE THREAD

**Issue by FrancescoCioria** [vieron/stylelint-webpack-plugin#47]
After updating `stylelint` to `v7.7.0` I see this error:
![image](https://cloud.githubusercontent.com/assets/4029499/21293895/8a957ba4-c530-11e6-9195-027d33c9e077.png)

In this version `stylelint` has exposed its formatters through documented API (see https://github.com/stylelint/stylelint/pull/2190/files). Do you think this could be the issue?

**Comment by JaKXz** [comment]
`+ stylelint-webpack-plugin@0.4.2` published! Thanks for reporting this and thanks @jeddy3 for the suggestion about the public API!
